# --- Created by Ebean DDL
# To stop Ebean DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table account_model (
  id                            bigint generated by default as identity not null,
  name                          varchar(255) not null,
  email                         varchar(255) not null,
  constraint pk_account_model primary key (id)
);


# --- !Downs

drop table if exists account_model;

