# --- Created by Ebean DDL
# To stop Ebean DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table account_model (
  id                            bigint generated by default as identity not null,
  uid                           uuid not null,
  first_name                    varchar(255) not null,
  last_name                     varchar(255) not null,
  email                         varchar(255) not null,
  email_validated               boolean default false not null,
  role                          integer not null,
  constraint ck_account_model_role check ( role in (0,1)),
  constraint uq_account_model_uid unique (uid),
  constraint pk_account_model primary key (id)
);


# --- !Downs

drop table if exists account_model;

